pipeline{
 agent any
 environment {
    ANYPOINT = credentials('anypoint.credentials')
 }
 stages {
 	stage ('Build'){
 		steps {

 				sh 'mvn -f mule-jenkins-pipeline/pom.xml clean install'

 		}
 	}
 	stage ('Deploy'){
 		steps {

 				sh 'mvn -f mule-jenkins-pipeline/pom.xml package deploy  -Dusername=$ANYPOINT_USR -Dpassword=$ANYPOINT_PSW -Denvironment=Development -DmuleDeploy'

 		}
 	}
 }

}
